### ISSUE TITLE
Osmosis with express?

### ISSUE THREAD

**Issue by ronihcohen** [rc0x03/node-osmosis#11]
Hey,

Maybe it's a stupid question but I`m trying to use osmosis inside 'app.get' function but it's working only once, is there a way to reset osmosis and initialize it more then once? 

Thanks, great project!

**Comment by rc0x03** [comment]
Version 0.0.5 handles new instances much better now. Please update and try that one instead. If the problem still persists please post your code and I'll take a look at it.

**Comment by ninozhang** [comment]
👏

**Comment by ninozhang** [comment]
Love U So Much!
I use Osmosis in my new project and I am facing the same problem as @ronihcohen does and come to here to check if there any solution.
And VERY lucky that you just solve it and it now works well in my project.
Thank You!
Gread JOB!

**Comment by ronihcohen** [comment]
Great! :+1:
