### ISSUE TITLE
Multiple sets on the same page

### ISSUE THREAD

**Issue by achimkoellner** [rc0x03/node-osmosis#21]
I'm trying to scrape multiple sets from one and the same page.
Imagine scraping all hrefs from a <menu> tag and then all hrefs from an <aside> tag.
I want to avoid making two GET requests to do that.

In my opinion the command chain would look this ...

    page = osmosis.get(pageUrl)
    
    .find('menu')
    .set({ 
        // get the <menu> links
    })
    .data(function() {
        // do something with the <menu> links
    })
    
    .find('aside')
    .set({ 
        // get the <aside> links
    })
    .data(function() {
        // do something with the <aside> links
    })
    
    .then(function() {
        // ... finally write everything to disk
    });

... but .find('aside') doesn't get the whole context passed. 

How would I do that with osmosis (not using another promise or a generator)?

**Comment by rc0x03** [comment]
In earlier versions of Osmosis `.find` would search the entire document. Currently, `.find` is relative to the previous context, so `.find('aside')` is actually looking in the `.find('menu')`. Having `.find` be relative to the current context might be slightly better from a performance standpoint, but obviously it's not clear enough that it's relative. Maybe in the next version `.find` will be made to search the entire document and another command will be available for the cases where you specifically want to search the current context. The question is the proper name for the command. I think `.child()` would due but it doesn't imply a search.

For right now you can call `.doc` to reset the current context:
```javascript
page = osmosis.get(pageUrl)

.find('menu')
.set({ 
    // get the <menu> links
})
.data(function() {
    // do something with the <menu> links
})

.doc()

.find('aside')
.set({ 
    // get the <aside> links
})
.data(function() {
    // do something with the <aside> links
})

.then(function() {
    // ... finally write everything to disk
});
```

**Comment by achimkoellner** [comment]
rc0x03, ah, that's what I was looking for! thank you.

One thing about that example is still a bit odd - when I use .doc() it seems to reset the context and i can find <aside> in a second run, but the 2nd .set().data() seems to *merge* the response parameter for .data() with the data of the first set. So looks like "data" is passed down the chain. Would there be a way to reset it as well?

eg. if the first call of .set() finds something link 

	{ link: 'myMenuLink1' } 

and the second .set() finds something like { }

	{ otherLlink: 'myAsideLink1' } 

The parameter of the 2nd .data( function(parameter) {...} ) call looks like this

	{ 
		link: 'myMenuLink1',
		otherLlink: 'myAsideLink1'
	 }

**Comment by rc0x03** [comment]
Maybe if `.data` is called without any arguments it should reset the data object. Maybe it would look more clear if the data object could be set by passing an object and not a function, then a reset would look like `.data({})` or `data(null)`. Yet another feature for a future release.

This should work for now: 
```javascript
.then(function(context, data, next) {
    next(context, {}, next);
})
```

**Comment by achimkoellner** [comment]
thank you rc0x03 - this works as a workaround.

**Comment by robert26bussard51** [comment]
RÖB

**Comment by specious** [comment]
I'm getting:
```
  .doc() // reset the context
   ^

TypeError: osmosis.parse(...).find(...).set(...).data(...).doc is not a function
```

osmosis 1.1.4

Was it removed?

**Comment by specious** [comment]
I've got a situation like @achimkoellner, I want to reset the data, so it doesn't accumulate.

**Comment by specious** [comment]
@rchipka, I'm successfully [using](https://github.com/specious/facebook-friends/blob/c493f9aaf2a12f659ef898a27b71083bc2c1da9a/index.js#L51) your [suggestion](https://github.com/rchipka/node-osmosis/issues/21#issuecomment-93947759).

I think a function officially dedicated to clearing the data would be of great help.
