### ISSUE TITLE
How to validate the request config?

### ISSUE THREAD

**Issue by zzyymaggie** [rc0x03/node-osmosis#28]
I set the request config via https://github.com/rc0x03/node-osmosis/wiki/01.-The-command-chain, 
```
 osmosis
 .config({
    tries: 3,
    timeout: 1000,
    proxy: 'http://localhost:8889',
})
.get(url);
```
but the result is that the request config do not work

**Comment by rc0x03** [comment]
This was due to the fact that `needle` doesn't use the default `proxy` option when no other proxy option is present. This should be fixed in Osmosis 0.0.8.

To verify config settings you can pass `config` a callback function:
```javascript
osmosis
.config({ proxy: 'localhost:8080' })
.config(console.log)
```
