### ISSUE TITLE
`done` not being called

### ISSUE THREAD

**Issue by matt2323** [rc0x03/node-osmosis#30]
It looks like done isn't begin called anymore in the current version of the code. 

I moved a project to a different system and it didn't work. I did a diff and it looks like a change to promise.js might have broke it. Using the old code in node_modules2 done works for me. I could be doing something wrong though, this is my first node project :) 

 diff -bur node_modules/osmosis/lib/promise.js node_modules2/osmosis/lib/promise.js
--- node_modules/osmosis/lib/promise.js 2015-04-12 01:13:06.000000000 +0000
+++ node_modules2/osmosis/lib/promise.js        2015-06-07 01:51:50.476756092 +0000
@@ -63,6 +63,7 @@
                                p.name = name;
                                p.cb = cb;
                                p.args = args;
+                               p.stackPending = false;
                                return p.next;
                        }else{
                                this.instance = ++instances;
@@ -75,6 +76,7 @@
                this.next.depth = this.depth+1;
                this.next.prev = this;
                this.args = args;
+               this.stackPending = false;
 
                if (typeof this.initialized === 'function') {
                        this.initialized(this);
@@ -160,16 +162,20 @@
 };
 
 Promise.prototype.start = function(context, data) {
+       if (this.stackPending === true) {
+               parser.stack--;
+               this.stackPending = false;
+       }
        if (context === null || this.next === undefined)
            return;
        if (context === undefined && this.depth !== 0) {
                this.error('no context');
        }else if (this.cb !== undefined) {
-               if (context !== undefined)
+               if (this.next.stackPending === false) {
                parser.stack++;
+                       this.next.stackPending = true;
+               }
                this.cb(context, extend({}, data));
-               context = null;
-               parser.stack--;
        }
 }

**Comment by rc0x03** [comment]
Could you post your code?

**Comment by matt2323** [comment]
I'm working putting together an example program, but it's proving to be harder than I thought. I can still reproduce it in my main project but not a sample one. I'll keep working on it.

**Comment by rc0x03** [comment]
Try updating to Osmosis version 0.0.7 and see if that will solve the issue.

**Comment by matt2323** [comment]
That fixed it for me. Thank you very much.
