### ISSUE TITLE
osmosis.js not found and osmosis.get is not a function

### ISSUE THREAD

**Issue by dsinghvi** [rc0x03/node-osmosis#31]
Hi, I am trying to use node-osmosis in a script for an html file. 
I have created a directory and executed the command: npm install osmosis. 
Next, I copy-pasted the craigs list script given and am attempting to see if that works. 
The first error I got was that "require is not defined". 
I proceeded to download require js, and used the command: npm install requirejs. 
Then in my html file before I ran the craigs list script, I loaded the require.js. 
Now, my HTML code looks like the following: 
![image](https://cloud.githubusercontent.com/assets/10870189/8049654/c1c8b80c-0e2f-11e5-9425-2e55b6196802.png)
 (testing.js is just the craigs list code)
The errors I am getting now include 
1) Osmosis.js not found
2) osmosis.get is not a function

Do you have any recommendations about what to do ?

**Comment by rc0x03** [comment]
Looks like you are trying to run Osmosis in a browser. Unfortunately, Osmosis is only intended to run on NodeJS and currently has no plans to support use in a browser.

**Comment by dsinghvi** [comment]
Ah, I see. Thanks a lot for your help.
