### ISSUE TITLE
Osmosis + Nock support

### ISSUE THREAD

**Issue by matiassingers** [rc0x03/node-osmosis#33]
I wasn't really sure where I should create this issue, so I created it on both projects. See https://github.com/pgte/nock/issues/335

----

I'm facing some issues using [Osmosis] and [Nock] for mocking HTTP responses in my unit tests, see the build failing on [Travis](https://travis-ci.org/matiassingers/spotify-countries). The `before` timeout in mocha gets triggered because [Osmosis] is encountering an error in the request/parsing.

I've written the smallest reproducible test case I could come up with, based on the failing build above.

### test case
```js
var osmosis = require('osmosis');
var nock = require('nock');

nock('https://www.spotify.com')
  .get('/select-your-country/')
  .reply(200, 'whatever');

osmosis
  .get('https://www.spotify.com/select-your-country/')
  .find('.country-list .country-item .country-link')
  .set({
    countryCode: '@rel'
  })
  .error(console.error)
  .done(function(){
    // never reaches here :sadface:
    console.log('it works!');
  });
```

### error
```sh
(get) TypeError: Cannot read property '_hasBody' of undefined
[get] https://www.spotify.com/select-your-country/ tries: 1 - Cannot read property '_hasBody' of undefined
    at /Users/matiassingers/dev/osmosis-nock-5226/node_modules/osmosis/index.js:150:35
    at done (/Users/matiassingers/dev/osmosis-nock-5226/node_modules/osmosis/node_modules/needle/lib/needle.js:355:7)
    at PassThrough.<anonymous> (/Users/matiassingers/dev/osmosis-nock-5226/node_modules/osmosis/node_modules/needle/lib/needle.js:523:9)
    at PassThrough.emit (events.js:117:20)
    at _stream_readable.js:943:16
    at process._tickCallback (node.js:419:13)
```

### possible bug
The offending lines in [Osmosis] look like this:
```js
if (!res.socket._httpMessage._hasBody || data.length == 0)
  throw(new Error('Document is empty'))
```

`res.socket` contains no `_httpMessage` property when returning the mocked response from [Nock], this is the entire object:
```js
{ domain: null,
  _events: {},
  _maxListeners: 10,
  writable: true,
  readable: true,
  setNoDelay: [Function: noop],
  setTimeout: [Function],
  _checkTimeout: [Function],
  setKeepAlive: [Function: noop],
  destroy: [Function: noop],
  resume: [Function: noop],
  getPeerCertificate: [Function: getPeerCertificate] }
```

----

The question then is:
- Is [Nock] mocking the requests wrongly by not including the `_httpMessage._hasBody` property?
- Or shouldn't [Osmosis] be checking for this property at all? Might be deprecated or something.

[Osmosis]: https://github.com/rc0x03/node-osmosis
[Nock]: https://github.com/pgte/nock

**Comment by matiassingers** [comment]
@rc0x03 it would be great to hear why you are actually checking these private properties?

**Comment by rc0x03** [comment]
This check was included during a test of different document formats. The reference to `res.socket._httpMessage._hasBody` will be deleted in Osmosis version 0.0.8.

**Comment by matiassingers** [comment]
@rc0x03 sounds great!

Any plans to change the current versioning strategy, to something that complies a little more with [SemVer](http://semver.org/)?
