### ISSUE TITLE
Dealing with parsing errors arising from malformed web pages.

### ISSUE THREAD

**Issue by miqid** [rc0x03/node-osmosis#34]
I've been trying to get Osmosis up and going to crawl through some data on a website which unfortunately has malformed DOM trees in some areas. I've used the `then` call to inspect the context and discovered a whole bunch of libxml parsing error objects. Data which I need to continue crawling is inevitably lopped off due to bad parsing.

I noted in another issue that fetching the raw HTML response from the context is not supported, which is unfortunate because I think I could pull some cringe-worthy regular expression voodoo to get the data I need to continue crawling.

I was wondering if I missed anything in Osmosis which would let me grab any HTML that libxml has not been able to parse successfully.

Thanks in advance.

**Comment by reimund** [comment]
If we could just pass a function to osmosis that would be called on the data before passing it to libxml we should be able to post-process the malformed data into valid input. Could a patch for this be accepted?

**Comment by rc0x03** [comment]
As of Osmosis 0.0.9 the `process_response` option can be set to `function(data) { ... }`. The `data` argument will be the HTTP response buffer. The callback should return the modified data.
