### ISSUE TITLE
Clicking JS-only elements/links/buttons

### ISSUE THREAD

**Issue by bfred-it** [rc0x03/node-osmosis#35]
Is this possible? I hit a wall now, osmosis doesn't seem to have a generic `.click()` method

**Comment by bfred-it** [comment]
I guess considering #4 this isn't possible yet

**Comment by rc0x03** [comment]
Osmosis can already create a DOM object out of a libxml context and have scripts run against the DOM, however the DOM capabilities haven't been fully implemented yet. Once these features are fully implemented, Osmosis will include support for many DOM interactions such as `.click()` as well as advanced control over the resulting event callbacks.

**Comment by nelsammak** [comment]
Is this still not possible or are the DOM interactions available by now? If yes, could you give an example or a brief on how to use?
