### ISSUE TITLE
Using osmosis with multiple sites in parallel

### ISSUE THREAD

**Issue by ruimgoncalves** [rc0x03/node-osmosis#37]
Hi

I have an express api that should return data scrapped from various sites depending on the express route.

But if multiple requests are executed at the same time or before one of theme is finished errors start being thrown, for example "Can't set headers after they are sent".

I believe this is because context are being passed from one osmosis instance to another. How can I separate entire osmosis instances so I can accomplish this?

some code from express
```javascript
app.get '/api/scrape/:site/:ref', (req, res, next) ->
  if req.params.ref.length < 7
    res.status(400).json 'error' : 'Invalid reference'
  else
    siteScrape = new require("./src/#{req.params.site}")
    siteScrape req.params.ref, (err, data)->
      if err
        res.status(400).json
          error : err.toString()
      else
        res.status(200).json data
  return
```

Thanks

**Comment by ruimgoncalves** [comment]
Here is some sample code demonstrating the problem
Toggle experiment value to see different results
In my case I cant get the results in parallel from the 2 sites, the problem gets worst if you use post requests.
Is there any workaround for this?
Thanks

```coffeescript
experiment = true

setTimeout ()->
  osm = require("osmosis")
  osm
    .get 'www.npmjs.com/search?q=scraper'
    .set
      query : 'input#site-search@value'
      packages : [
          osm.find 'ul.search-results li'
            .set
              name : '.package-details h3 a.name'
              description : '.package-details p.description'
      ]
    .data (listing)->
      console.log listing
    .error (info)->
      console.error "erro npmjs", info
, if experiment then 10 else 0

setTimeout ()->
  osm = require("osmosis")
  osm
    .get 'www.craigslist.org/about/sites'
    .set
      'location' : ['h1 + div a']
    .data (listing)->
      console.log listing.location.length
    .error (info)->
      console.error "erro craigslist", info
, if experiment then 0 else 10
```

**Comment by cezary** [comment]
Pretty sure I'm running into this same problem; parsing multiple sites concurrently with osmosis, only the last calls done.

**Comment by andineck** [comment]
I'm experiencing the same problem, but have no Idea how to fix it... Anyone?

**Comment by rc0x03** [comment]
@cezary this is a known behavior of Osmosis. Osmosis only keeps a global stack count, so only the last instance will call `done`. There's no bulletproof way of implementing per-instance stack counting because there are many scenarios where a "done" instance can start back up again. The only way to really know is when the actual Document objects are being garbage collected. I've been adding features to libxmljs that will allow osmosis to have much more functionality. One of my next `libxmljs` pull requests will probably be a callback function for the Document destructor. This will allow for accurate per-instance stack counting and `done` calling.

**Comment by rc0x03** [comment]
I'll be looking into this issue as soon as I can.

**Comment by andineck** [comment]
:+1:  thank you!

**Comment by rc0x03** [comment]
This should be fixed in the latest version of Osmosis
