### ISSUE TITLE
Accessing JavaScript Variables

### ISSUE THREAD

**Issue by omidfi** [rc0x03/node-osmosis#4]
Hi, 
I currently use casper/phantom's evaluate function to read global JavaScript variables from the page. It's slow, but still easier than scraping script tags manually with regex to get out vars. 

Does Osmosis have something to offer in that direction?

**Comment by rc0x03** [comment]
Unfortunately Osmosis isn't capable of doing this yet. It would be entirely possible to create `window` and `document` objects and link their functions and properties to the libxmljs equivalents. This would allow you to then run the code in its own context using (vm.runInContext)[https://nodejs.org/api/vm.html] and extract all the global variables. In the future, something like `osmosis.dom` could create a functional DOM out of a context object. The DOM object could then have any scripts run against it as if it were a browser.

Here's what it might look like:
```javascript
var osmosis = require('/root/node-osmosis');
var vm = require('vm');

osmosis
.get('example.com') 
.find('script')
.then(function(context, data, next) {
    
    // get the content of the <script> element
    var script = context.content();
    
    // get the current libxml Document
    var doc = context.doc();
    
    // convert the Document a DOM object
    var dom = osmosis.dom(doc);
    
    // run the <script> against the DOM
    vm.runInContext(content, vm.createContext(dom));
    
    // retrieve the newly created global variables
    for (key in dom) {
        if (key == 'document' || key == 'window')
            continue;
        data[key] = dom[key];
    }
})
.data(function(vars) {
    console.log('found variables:', vars);
})
```

**Comment by omidfi** [comment]
I see. Thanks for your explanations. I like osmosis. Keep up the good work!
