### ISSUE TITLE
how to catch errors?

### ISSUE THREAD

**Issue by maxlath** [rc0x03/node-osmosis#40]
Hi, thank you for this great lib!
I couldn't find an equivalent to other promises libs `.catch` or `.fail` to handle errors, is there something like that?
If not, as I'm using Bluebird, I was thinking to wrap Osmosis promises in a Bluebird promise, any reasons why it wouldn't be a good idea?
thanks in advance!
Max

**Comment by rc0x03** [comment]
You can use [.error](https://github.com/rc0x03/node-osmosis/wiki#error) to log or handle errors. I don't see any reasons why wrapping it would cause problems.

**Comment by maxlath** [comment]
oh right, didn't see that. Thanks!
