### ISSUE TITLE
Dynamic .get() URLs

### ISSUE THREAD

**Issue by jdufour** [rc0x03/node-osmosis#42]
I'm failing a bit at getting data to pass into the .get, the url isn't directly encoded from the web page but rather a constructed url using an id number.  I tried using data to construct it, but wasn't able to pass it to the get command.  Thoughts?

    .get(init)
    .follow('div.name > a')
    .set({
        'someNo': 'tr.no'
    })
    .data(function(data) {
        data.url = 'http://somesite'+ data.someNo + 'moreurl'
    })
    .get(data.url)

Which fails because no data.url is undefined.

How might I go about passing data to the .get?

Best Regards

**Comment by rc0x03** [comment]
The next version accepts a callback function as the first argument for `.get`. So you will be able to do this:

```javascript
.get(function(context, data) {
    return data.url
})
...
```

**Comment by rc0x03** [comment]
The solution mentioned above is supported in the latest version.

**Comment by jdufour** [comment]
Thanks!  Much appreciated!

**Comment by rc0x03** [comment]
The latest commits supports a callback function as the URL argument as well as a formatted string.

```javascript
.get(init)
.follow('div.name > a')
.set({
    'someNo': 'tr.no'
})
.get('http://somesite.com/%{someNo}/moreurl')
```
