### ISSUE TITLE
Support for nested objects in array?

### ISSUE THREAD

**Issue by stephengardner** [rc0x03/node-osmosis#44]
In the example, you use `.find` and `.set` to populate an array of image URLS (strings) - that's great - but what if I want to populate an array of objects?  Let's say I want to save an array of images as:
`[ { src : String, title: String } ]`.  Any support for this?
If not, a decent syntax might be: `images[].src : a@href, images[].title: a@title`.  (perhaps), or: `"images[]" : { src : "a@href", title : "a@title" }`

**Comment by rc0x03** [comment]
This is supported. See (https://github.com/rc0x03/node-osmosis/wiki#set)[set]
