### ISSUE TITLE
What's the correct way to handle missing data?

### ISSUE THREAD

**Issue by reimund** [rc0x03/node-osmosis#46]
Whenever one of my find-commands fails and gives me "(find) no results for ____" Osmosis seems to abort the chain.

I tried catching the error with .error, but my subsequent find/data commands are still ignored.

What's the correct way to make Osmosis continue, ignoring the missing data?

I'm doing something like:

```javascript
osmosis
	.get(url) 
	.find(...)
		.set(...)
	.follow(...)
		.find(...)
			.set(...)
		.find(...) // This selector does not always resolve
			.set(...})
		.find(...) // This doesn't seem to run if the above fails
			.set(...)
	.follow('a@href') // Neither does this
		.find(...)
			.set(..)
	.data(function(stuff) {
		// And I never get here :(
	})
	.done(function() {
		// But I do get here...
	})
```

**Comment by reimund** [comment]
Seems like calling `next` in a `then` block after the failing `set` does the trick.

Eg:
```javascript
osmosis
    .get(url) 
    .find(...)
        .set(...)
    .follow(...)
        .find(...)
            .set(...)
        .find(...) // This selector does not always resolve
            .set(...})
        .then(context, data, next) {
            next(context, data);
        }
        .find(...)
            .set(...)
    .follow('a@href')
        .find(...)
            .set(..)
    .data(function(stuff) {
        ...
    })
    .done(function() {
        ..
    })
```

**Comment by rc0x03** [comment]
There isn't an official way to handle missing data. By default, Osmosis assumes that if one link in the chain fails, any subsequent commands will fail. This obviously isn't always the case. I'll be working on a solution to this.

**Comment by rc0x03** [comment]
The next version of Osmosis is planned to have `.do()`. This command will allow one or more nested instances to run from the current context and return to the next command regardless of whether any of them failed.

```javascript
osmosis.get(url)
...
.do(
    osmosis... ,
    osmosis... ,
    osmosis...
)
...
```

**Comment by rc0x03** [comment]
Supported in 0.1.0
