### ISSUE TITLE
Logging into a page with basic http authentication?

### ISSUE THREAD

**Issue by jcwren** [rc0x03/node-osmosis#48]
I'm doing a little web page automation, but I need to log in to the page using basic http authentication first. I can do this with node-request, but either I haven't figured out how with osmosis, or even if osmosis supports it. 

Any advice, hints or tips?

**Comment by rc0x03** [comment]
Osmosis uses Needle which has support for basic authentication.

You can configure it by using either of these methods:
```javascript
osmosis.config({ username: 'user', password: 'pass' })
...

osmosis.get('example.com', null, { username: 'user', password: 'pass' })
```
