### ISSUE TITLE
Ajax selection

### ISSUE THREAD

**Issue by grinono** [rc0x03/node-osmosis#50]
It's a great scraping solution but what if their is ajax loaded content in the page?

i tried the following but somehow it's not returning any data

osmosis
.get('http://tweakers.net/pricewatch/') 
.find('.large a')
.set('product')
.data(function(listing) {
    console.log(listing);
})

Any idea?

**Comment by rc0x03** [comment]
I tried your example with the latest version (0.0.9) and it seems to be working without DOM capabilities. Osmosis 0.0.9 has `.click(selector)` and `.dom()` and will have many more DOM commands in the future.
