### ISSUE TITLE
How to write data to json file.

### ISSUE THREAD

**Issue by y0unghe** [rc0x03/node-osmosis#52]
How to write data to json file.
```
.data(function(listing) {
    jsonfile.writeFileSync(file, listing);
})
```
I know there is a done function, but if there is a error in the scraping process, this function will never be called, but I don't want to lose previous scraped data. So How to write data to json file?

**Comment by rc0x03** [comment]
As of Osmosis 0.1.0, you can call `.do(...)` with Osmosis instances as arguments. Each instance will be called with the current context. All instances will be called and `.do()` will call `next()` regardless of any errors. If you execute an error prone call with `.do(...)` instead, you will still get the data at the end.

Also, it may help to know that `.data()` can be called at any point along the command chain.
