### ISSUE TITLE
Http Proxy Rotation

### ISSUE THREAD

**Issue by larron** [rc0x03/node-osmosis#53]
Hey @rc0x03 ,

Awesome library! After browsing osmosis and needle docs / code it doesn't appear to me that there's a way to rotate your http proxies.  Let's say that I've got a list of 100 http proxies and I'd like to have Osmosis randomly select one per each needle request or use a round robin etc..  Is there any way to currently do this?  If not, is this something you are open to?

Thanks

**Comment by rc0x03** [comment]
This is something I plan on adding to the next version of Osmosis. The proxy option can be an array (Osmosis will select the next working proxy if one fails) or a callback function that will return a proxy URL. I'll close this issue once this feature has been implemented.

**Comment by larron** [comment]
Awesome! Thanks Robbie.

**Comment by rc0x03** [comment]
Added in version 0.1.0
