### ISSUE TITLE
How to edit follow url

### ISSUE THREAD

**Issue by y0unghe** [rc0x03/node-osmosis#61]
I have a url and I need to edit it so osmosis could follow and parse the results. Where should I do the string manipulation and pass it to the follow() function?

**Comment by rc0x03** [comment]
You can rewrite URLs like this:

```javascript
osmosis
.follow(...)
.rewrite(function(url) {
// return modified url string
})
```

**Comment by Cu4rach4** [comment]
Hi @rchipka so sorry to open again, but i try to change a href url with rewrite, but nothing happens...

`.follow('.coco:first a@href').rewrite(function(url) {
			// return modified url string
			//console.log('url: ',url);
				return url.replace('ProductsAjax','Products')
			})//`
