### ISSUE TITLE
How can i contact you

### ISSUE THREAD

**Issue by gragra100** [rc0x03/node-osmosis#69]
Hi i am very interested about your work, how can i contact you for a donation? I wrote this issue because i didn't found your email on your git-hub profile and i need to talk with you before the donation.

**Comment by taojack** [comment]
Love to hear from the author too. We will gladly send you $15 or more to support your work and have you help us get better on writing some scrapper.

**Comment by rc0x03** [comment]
Thank you for your interest in supporting Osmosis. I've updated my GitHub profile to include my email address. You may contact me via email or by writing a message in the PayPal donation form. Thanks again.
