### ISSUE TITLE
Branching

### ISSUE THREAD

**Issue by obsidience** [rc0x03/node-osmosis#71]
First off, thanks for work with this framework - kudos.

What would be the best way to branch while scraping a site?  The examples on the homepage and wiki show, what seem to be very linear navigation path versus my goal of going to a page and then navigating to many different types of links within that page using different logic based on the type of page being linked to.

My current plan, which may be utterly wrong is to use .data(function(listing)){} and with the listing object - call other method (promises) that will create a new node-osmosis instance to perform their scraping.

But it seems more ideal if this was either built-in, or I could somehow pass in a reference or clone of node-osmosis or even just the context to reduce redundancy.

Help appreciated!

**Comment by rc0x03** [comment]
Osmosis instances can be nested within `.set`. If the nested instance also calls `.set`, the "return value" of the nested instance will be the data object of the nested `.set`. If the nested instance calls set on more than one context, the "return value" of the nested instance is an array of data objects from the nested `.set`. To ensure that an array is always set, wrap the the nested instance in an array `[]`. If the nested osmosis instance doesn't call set, its "return value" is the context(s). If a single context is returned, the "return value" will be a string containing the text content of the context. If mutiple contexts are returned, the data value will be an array of strings.

For some examples look at the wiki page and also the `.set` [tests](https://github.com/rc0x03/node-osmosis/blob/master/test/set.js)

**Comment by obsidience** [comment]
OK that makes sense.  I was going down a different route of creating an object graph without using `.set`.  I'm going to try to convert over to that.

Thank you very much!

**Comment by rc0x03** [comment]
You're welcome. The `.set` command should fill any need to set data. Filtering or processing can be done along the command chain with `.then` or at the end with `.done`.
