### ISSUE TITLE
Selector context?

### ISSUE THREAD

**Issue by MMRandy** [rc0x03/node-osmosis#72]
How do you select things within the context of another selector?  It appears that "find" only selects thing globally and not within the scope it's being called.  I see a "do" function, but the documentation is so sparse it's hard to discern it's intended use.

I am currently comparing scraping engines out there and I have a simple demo scenario:  create an array of nested objects that hold the Craigslist countries, states, and cities.  Like this:
```
[
   {
      "regionCode":"US",
      "region":"US",
      "states":[
         {
            "name":"Alabama",
            "cities":[
               {
                  "name":"Auburn"
               },
               {
                  "name":"Birmingham"
               },
		….etc…
            ]
         },
         {
            "name":"Alaska",
            "cities":[
               {
                  "name":"Anchorage / mat-su"
               },
               {
                  "name":"Fairbanks"
               },
		…etc…
            ]
         },
	  …etc…
      ]
   },
   {
      "regionCode":"CA",
      "region":"Canada",
      "states":[
         {
            "name":"Alberta",
            "cities":[
               {
                  "name":"Calgary"
               },
		…etc…
            ]
         },
         {
            "name":"British Columbia",
            "cities":[
               {
                  "name":"Cariboo"
               },
		…etc…
            ]
         },
	 …etc…
      ]
   },
   {
      "regionCode":"EU",
      …etc…
   },
   {
      "regionCode":"ASIA",
      …etc…
   },
   {
      "regionCode":"OCEANIA",
      …etc…
   },
   {
      "regionCode":"LATAM",
      …etc…
   },
   {
      "regionCode":"AF",
      …etc…
   }
]
```

I am able to get this working with Osmosis with the following code:
```
var osmosis = require('osmosis');

module.exports = function(request, reply){
    var list = [];
    var arrStates = [];
    osmosis
        .get('www.craigslist.org/about/sites')
        .find('h1')
        .set({
            regionCode: 'a@name'
        })
        .then(function(context, data, next, done){
            arrStates = [];
            var states = context.find('+ div > div > h4');
            states.forEach(function(state) {
                var arrCities = [];
                var cities = state.find('+ ul > li');

                cities.forEach(function(city){
                    arrCities.push({
                        name: city.text().charAt(0).toUpperCase() + city.text().slice(1)
                    });
                    next(city, data);
                });

                arrStates.push({
                    name: state.text(),
                    cities: arrCities
                });
                next(state, data);
            });
            data.region = context.text();
            data.states = arrStates;

            list.push(data);

            done();
        })
        .done(function(data){
            reply(list);
        });
};
```
However, I don't really like having to resort to the "then" method and fall back to full on JS programming.  I'm looking to be more declarative in what I can pass to a scraping engine and have that engine handle the scraping and packaging of data in as succinctly as possible.

For instance, here is the same demo task performed in x-ray:
```
var Xray = require('x-ray');
var x = new Xray();

module.exports = function(request, reply){
    x('http://www.craigslist.org/about/sites', 'h1', [{
        regionCode: 'a@name',
        region: '',
        states: function($, cb) {
            return x($.next(), 'h4', [{
                name: '',
                cities: function($, cb2) {
                        return x($.next(), 'li', [{
                            name: 'a'
                        }])(cb2);
                    }
                }])(cb);
            }
    }])(
        function(err, obj){
            reply(obj);
    })
};
```
That is very succinct for the same task, and it's easy to see how $ is passed down into the sub-context operations so selectors are relative to their current scope.  This really helps to keep the code small and clean.

Now, when I do some very preliminary perf tests, it appears that the Osmosis code completes the job 2-3 times faster than x-ray.  That is pretty hard to ignore.  So, I'm wondering if my code above for Osmosis can be improved upon to be more succinct and declarative in nature.  

You certainly have done a lot of work here on this lib.  I think you would help further your work by creating more examples against your API functions so end users like me wouldn't have to bother you as much :)

In any event, thanks for sharing the lib!

**Comment by rc0x03** [comment]
The `.find` command will always search the document context **unless** it is nested within `.set`, in which case it will search current context.

Well... that's how it's **supposed** to behave, however the condition that determined whether it was nested seems to have been removed in the previous release :weary:. I've created a test for this to ensure that it can't happen again.

Until the next release, the best workaround is to use the undocumented (yes, I am aware of this) **.select** command. It's exactly the same as `.find`, but uses the current context.

But anyways, here's what you're looking for:
```javascript
osmosis.get('www.craigslist.org/about/sites')
.set({
    countries: [
        osmosis
        .find('h1')
        .set('region')
        .set({
            'regionCode': '@name',
            'states': osmosis.select('+ .colmask h4').set('name')
                .set({ 'cities': osmosis.select('+ ul a').set('name')
                     .set('link', '@href')
                })
        })
    ]
})
```

Again, in the next release you won't have to use `.select` for nested instances.

As for the documentation issue, I am aware that it is very lacking and I apologize.

I'd like to switch my focus to improving the documentation and creating tutorials when I can fully answer questions like:

 * Should `.select` even be a command (can it always be replaced by `.set(... osmosis.find() ...)`)?
 * Should `.select` be called `.select`? Is there a more clear/indicative name?
 * What are the limitations of the XPath/CSS selector technology (if any)?
 * What are the limitations of nesting Osmosis instances (can they only go in `.set`)?
 * Does every implemented command have comprehensive tests?
 * Does the DOM have standards compliance tests?
 * Does the internal command API initialize Window objects using a single, consistent technique?

Anything that could change the way users interface with the API could break documentation and tutorials, so I'd like to make design choices that allow for flexibility in the future.

A lot of my energy goes into thinking about how Osmosis features **should** work, rather than just making them work. This can take a while, but I think it's worth it in the end.

**Comment by MMRandy** [comment]
Well that helps a ton, thanks for that.  Couple questions.  My company does a LOT of scraping, and there are many, many times where you need to manipulate the scraped data in some form or fashion:

Question #1:  Have you thought about allowing manipulation of the value as the scraping is happening, rather than wait until the .data() method?  If you have to wait for .data(), you will have create new transformation logic to recycle the same structures...which seems a bit redundant.  Not sure how you'd do it, but maybe something along the lines of allowing chaining of normal data prototype methods, like so:
```
...
            'states': osmosis.select('+ .colmask h4')
                .set('name')
                .set({
                    'cities': osmosis.select('+ ul a')
                        .set('name')**.toUpperCase()**
                        .set('link', '@href')
                })
...

```

Question #2: Do you always have to chain a .data(callback) and .done(callback) together to get the results of what has been collected in a nested hierarchy?  For instance, here is my code now:
```
var osmosis = require('osmosis');
module.exports = function(request, reply){
    var list = [];

    osmosis.get('www.craigslist.org/about/sites')
        .find('h1')
        .set({
            'region': 'text()',
            'regionCode': 'a@name',
            'states': osmosis.select('+ .colmask h4')
                .set('name')
                .set({
                    'cities': osmosis.select('+ ul a')
                        .set('name')
                        .set('link', '@href')
                })
        })
        .data(function(data){
            list.push(data);
        })
        .done(function(){
            reply(list);
        });
};
```
I need the root level to be an array or root objects, rather than an object with one root property "countries".  Is this the right way to do this?

Question #3:  What does the .do() method actually do?

Thanks again for your prompt response and this lib.

**Comment by MMRandy** [comment]
As far as the .select() goes, I would agree that the functionality between .select() and .find() would be too similar to warrant having both methods.  I actually like select() over find() because to me is seems to indicate that a context is being set with each selection better than the word "find".  That's just me though...I'm sure others would prefer .find() for their own reasons.

**Comment by rc0x03** [comment]
###Question 1:

Yes, I've considered some sort of inline data manipulation but I'm not sure how I could implement it. I could implement the basic string manipulation functions like `.replace`, `.substr`, `.split`, etc. However, if these simple functions don't do exactly what is needed, you'll end up writing a callback using `.then` anyways. Which, by the way, is the way I would currently do inline data manipulation.

```javascript
'cities': osmosis.select('+ ul a')
          .set('name')
          .then((callback, data, next) => {
               data.name = data.name.toUpperCase();
               next(context, data);
          })
```
Not the most elegant or easy to write solution, but it works.

Which reminds me, yet another undocumented (and untested at this point) feature of `.set` is to use a callback and return the value:

```javascript
'cities': osmosis.select('+ ul a')
          .set('name', function(context) {
              return context.getAttribute('name').toUpperCase();
          })
```

This solution is a little less painful than a callback using `.then`, but still probably not ideal. I'll add tests for it in the future. I still need to figure out what other arguments the callback should receive and if the value should be set by the return value or a function (for async stuff).

###Question 2:

While I was writing the test code for your original post, I realized that having a the root object be an array is a useful feature. I've implemented this and added some tests, so it should be available in the next version.

In other words, without nesting, you will be able to do `.set( [  selectors, instances, other array values...  ] )` and not just `.set( { key: value } )`.

###Question 3:

What the `.do` method "does" :confounded: :smile: Good question. This is a command that definitely needs a better name.

The first thing it can be used for is to send the same context to multiple commands. In this case you can use `.do` when you need to do lots of things with the current context and it doesn't make sense to do it within `.set`.

The next thing it can be used for is to survive failing commands. When a command along the chain fails, the following commands are never called. In this case, you can use `.do` when you want to pass your `context` and `data` to one or more instances that might fail, and still receive a single context at the end no matter what. This way you can set, modify, search, or do whatever and still continue on if one of the instances doesn't succeed.

That's the idea. Maybe it should be two separate ideas. Probably a different name. I'm open to any suggestions.

**Comment by rc0x03** [comment]
@MMRandy The `.find` command actually started off as a context relative search, however I saw that people were confused when `.find` wasn't working further down the chain. They didn't know that `.find` was still searching the current context. I guess the general assumption is that `.find` is a vague name and will "find" anything, so I changed it to search the entire document.

It's a little late in the game to remove `.find`, however I haven't documented `.select` yet for this very reason. If I can just come up with a name that says "findInThisContext" in one word... 

Another goal of this project is to make every command a single word. I figure that if it needs to be camelCased or under_scored then maybe the second word is better of as an argument to a simpler command.

**Comment by rc0x03** [comment]
@MMRandy Here's an even cleaner solution to your first question:

```javascript
'cities': osmosis.select('+ ul a')
          .set('name', city => city.getAttribute('name').toUpperCase())
```

I'm thinking this will be the accepted way to modify data in place.

**Comment by MMRandy** [comment]
I do like that better than the then, will have to convert my p.o.c. app over to ES6 which I planned to do anyway.

So city will be the selected context in the above scenario?  If so, that would work well I think.

**Comment by rc0x03** [comment]
@MMRandy Yes, the city would be current context (in this case `+ ul a`). I'll adding a bunch of documentation in the next release.

If you like Osmosis and depend on it, please consider a donation. Any contributions help keep the wheels in motion. Let me know if you run into any other issues.

**Comment by aditor** [comment]
Hi
