### ISSUE TITLE
Is it possible to .follow relative hrefs?

### ISSUE THREAD

**Issue by klatchbaldar** [rc0x03/node-osmosis#74]

**Comment by rc0x03** [comment]
Yes, `.follow` resolves all relative URLs based on the document URL

**Comment by klatchbaldar** [comment]
What is the pattern to match it?

**Comment by rc0x03** [comment]
To follow only local links you can use `.follow('a:local')`. To only relative URLs you can use `.follow('a@href:starts-with("/")')` or `.follow('a:path("/")')`. To follow only links that start with a certain path you can use `.follow('a:path("/some/dir/")')`.

**Comment by hielfx** [comment]
How can I tell osmosis what is the url to append to the relative path? I am using nested .set() and I can't figure how to put it to work (currently is trying to get localhost/relPath, witch doesn't exists)
