### ISSUE TITLE
Examples should hint that a final .done(callback) is required.

### ISSUE THREAD

**Issue by neo21670** [rc0x03/node-osmosis#9]
No examples hint that a final `.done()` is required to run without any errors. Without this, every scraping attempt ends up in a `TypeError: Cannot read property 'done' of undefined` error.

**Comment by rc0x03** [comment]
While `.done` is not intended to be required for a working osmosis parser, the most recent NPM version has a bug that causes an error without it. A new NPM update is coming soon that will fix this as well as add many new features. Until then you should use the latest commit.
